### ISSUE TITLE
como carajos se instala esa mierda

### ISSUE THREAD

**Issue by orillad** [BinarySandia04/Corona#2]
tengo un grave problema ns com instalar la mierda programa que hisite :-1:

**Comment by BinarySandia04** [comment]
debes descargarlo por la red peruana de datos de nada hermano B-)

**Comment by orillad** [comment]
con el servidor coreano no me funciona

**Comment by BinarySandia04** [comment]
prueba con el japonés es open source

**Comment by orillad** [comment]
passame el link de git para instalarlo

**Comment by BinarySandia04** [comment]
https://github.com/BinarySandia04/Corona.git

**Comment by orillad** [comment]
Esto no funciona e

**Comment by orillad** [comment]
g

**Comment by BinarySandia04** [comment]
H
